version: '3.8'

services:
  db:
    image: postgres:16.2
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: orders_database
    volumes:
      - ./postgres:/var/lib/postgresql/data
